### ISSUE TITLE
Cannot click on tooltip items

### ISSUE THREAD

**Issue by be5invis** [nk2028/tshet-uinh-autoderiver#25]
It is currently impossible to click on the tooltip items using pure mouse because the tooltip panel will disappear when the mouse moves to it (and leaves the character in the output panel).

**Comment by syimyuzya** [comment]
v0.2 is online now.

Do note that there is still a little margin between the tooltip and the charater, if move the mouse slowly up, the tooltip will still hide. This is however intended, in order to prevent the tooltip from completely blocking the content behind it (thus making it hard to see a character in the previous line).
